/*
 * ==========================================
 * |          GENERATED BY SUPAZOD          |
 * ==========================================
 */

import { z } from 'zod';
import * as generated from './src/schemas/database';
export type PublicExpiryType = z.infer<typeof generated.publicExpiryTypeSchema>;
export type PublicGroceryItemStatus = z.infer<
  typeof generated.publicGroceryItemStatusSchema
>;
export type PublicStorageLocation = z.infer<
  typeof generated.publicStorageLocationSchema
>;
export type PublicUnit = z.infer<typeof generated.publicUnitSchema>;
export type Json = z.infer<typeof generated.jsonSchema>;
